# Generated by Django 4.1.5 on 2023-02-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('wine_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('grape', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'db_table': 'wines',
                'ordering': ['name'],
            },
        ),
    ]
